apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-app
  namespace: node-docker-app
  labels:
    app: node-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-docker-app
  template:
    metadata:
      labels:
        app: node-docker-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
        - name: node-docker-app
          image: nileshpawar0212/node-docker-app:30 # placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

