apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-app
  labels:
    app: node-docker-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-docker-app
  template:
    metadata:
      labels:
        app: node-docker-app
    spec:
      containers:
        - name: node-docker-app
          image: your-dockerhub-username/node-docker-app:latest # placeholder
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

